routes/web.php
<?php

use App\Http\Controllers\ProfileController;
use App\Http\Controllers\MeshPhoneController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\PageController;
use App\Http\Controllers\DashboardController;
use Illuminate\Support\Facades\Route;
use App\Helpers\Helper;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    // frontpage.md needs to reside in the public directory
    if (file_exists('frontpage.md')) {
        $front_page = file_get_contents('frontpage.md');
    } else {
        $front_page = '';
    }
    return view('welcome', compact('front_page'));
});

Route::Resource('page', PageController::class)
        ->only(['show']);

require __DIR__.'/auth.php';

Route::get('/dashboard', [DashboardController::class, 'index'])
    ->middleware(['auth', 'verified'])->name('dashboard');

Route::get('/info', function() {
    return phpinfo();
});

Route::get('/usertest', function() {
    return view('usertest');
});

Route::middleware('auth')->group(function () {
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
});

Route::group(['middleware' => ['auth']], function() {
    Route::resource('roles', RoleController::class);
    Route::resource('users', UserController::class);
});

Route::get('/meshphone/search', [MeshPhoneController::class, 'search'])
    ->name('meshphone.search');
Route::resource('meshphone', MeshPhoneController::class)
    ->only(['index', 'create', 'store', 'edit', 'update', 'destroy'])
    ->middleware(['auth']);
Route::get('/meshphone/{id}/delete', [MeshPhoneController::class, 'destroy'])
    ->name('meshphone.delete')
    ->middleware(['auth']);
Route::Resource('meshphone', MeshPhoneController::class)
        ->only(['show']);

Route::get('/network_json', function () {
    return redirect('/api/network_json');
});
Route::get('/network_xml_v2', function () {
    return redirect('/api/network_xml_v2');
});
Route::get('/network_xml_v1', function () {
    return redirect('/api/network_xml_v1');
});

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use MongoDB\Laravel\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;
//use Illuminate\Foundation\Auth\User as Authenticatable;
use MongoDB\Laravel\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;
use Spatie\Permission\Traits\HasRoles;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable, HasRoles;

    protected $connection = 'mongodb';

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'callsign',
        'roles',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
        'password' => 'hashed',
    ];
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;;
use App\Http\Controllers\Controller;
use App\Models\User;
use App\Http\Requests\UserRequest;
use Spatie\Permission\Models\Role;
use DB;
use Hash;
use Illuminate\Support\Arr;
use Illuminate\View\View;
use Illuminate\Http\RedirectResponse;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request): View
    {
        $data = User::latest()->paginate(20);

        return view('users.index',compact('data'))
            ->with('i', ($request->input('page', 1) - 1) * 20);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(): View
    {
        $roles = Role::pluck('name','name')->all();
        return view('users.create',compact('roles'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request): RedirectResponse
    {
        $this->validate($request, [
            'name' => 'required',
            'email' => 'required|email|unique:users,email',
            'password' => 'required_with:confirm-password',
            'confirm-password' => 'same:password',
            'roles' => 'array',
            'callsign' => 'required|string|uppercase|max:6',
        ]);

        $input = $request->all();
        info($input);
        $input['password'] = Hash::make($input['password']);

        $user = User::create($input);
        $user->assignRole($request->input('roles'));

        return redirect()->route('users.index')
                        ->with('success','User created successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id): View
    {
        $user = User::find($id);
        return view('users.show',compact('user'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id): View
    {
        $user = User::find($id);
        unset($user->password);
        $roles = Role::pluck('name','name')->all();
        info(var_export($roles, true));
        //$userRole = $user->roles->pluck('name','name')->all();

        return view('users.edit',compact('user','roles'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UserRequest $request, $id): RedirectResponse
    {
        $this->validate($request, [
            'name' => 'required',
            'email' => 'required|email',
            'password' => 'required_with:confirm-password',
            'confirm-password' => 'same:password',
            'roles' => 'array',
            'callsign' => 'required|string|uppercase|max:6',
        ]);

        $input = Arr::except($request->all(), array('_token', '_method'));
        if(!empty($input['password'])){
            $input['password'] = Hash::make($input['password']);
        }else{
            $input = Arr::except($input,array('password', 'confirm-password'));
        }

        $user = User::find($id);
        $user->update($input);

        if (Arr::exists($input, 'roles')) {
            $user->syncRoles($input['roles']);
        } else {
            $user->syncRoles([]);
        }

        return redirect()->route('users.index')
                        ->with('success','User updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id): RedirectResponse
    {
        User::find($id)->delete();
        return redirect()->route('users.index')
                        ->with('success','User deleted successfully');
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;
use Illuminate\View\View;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     */
    public function render(): View
    {
        return view('layouts.app');
    }
}

resources/views/users/create.blade.php
<x-app-layout>
<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="pull-left">
            <h2>Create New User</h2>
        </div>
        <div class="pull-right">
            <a class="btn btn-primary" href="{{ route('users.index') }}"> Back</a>
        </div>
    </div>
</div>

@if (count($errors) > 0)
  <div class="alert alert-danger">
    <strong>Whoops!</strong> There were some problems with your input.<br><br>
    <ul>
       @foreach ($errors->all() as $error)
         <li>{{ $error }}</li>
       @endforeach
    </ul>
  </div>
@endif

<form method="POST" action="{{ route('users.store', $user->id) }}">
<div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>Name:</strong>
            <input type="text" name="name" id="name" class="form-control" value="">
        </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>Email:</strong>
            <input type="text" name="email" id="email" class="form-control" value="">
        </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>Password:</strong>
            <input type="password" name="password" id="password" class="form-control" value="">
        </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>Confirm Password:</strong>
            <input type="password" name="confirm-password" id="confirm-password" class="form-control" value="">
        </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>Role:</strong>
            <select name="roles[]" id="roles" class="form-controls" multiple>

            </select>
        </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12 text-center">
        <button type="submit" class="btn btn-primary">Submit</button>
    </div>
</div>
</x-app-layout>

resources/views/users/edit.blade.php
@php
    use Spatie\Permission\Models\Role;
    //$user = auth()->user();
    $all_roles = Role::all();
@endphp
<x-app-layout>
<div class="my-4">
    <div class="field-container mx-8">
        <div class="pull-left">
            <h2 class="mx-8">Edit User</h2>
        </div>
        <div class="pull-right">
            <a class="inline-block ml-2" href="{{ route('users.index') }}">
                <x-secondary-button>{{ __('Back') }}</x-secondary-button>
            </a>
        </div>
    </div>
</div>

@if (count($errors) > 0)
  <div class="alert alert-danger">
    <strong>Whoops!</strong> There were some problems with your input.<br><br>
    <ul>
       @foreach ($errors->all() as $error)
         <li>{{ $error }}</li>
       @endforeach
    </ul>
  </div>
@endif

<form method="POST" action="{{ route('users.update', $user->id) }}">
@csrf
@method('patch')
<table class="table-fixed mt-8 border-gray-500 mx-auto w-3/4">
    <tr><td>
        <label for="name">Name:
            @error('name')
                <span class="font-bold text-red-700" role="alert"><strong>{{ $message }}</strong></span>
            @enderror
            <input class="rounded-md focus:ring-2 invalid:border-red-500
                {{ $errors->has('name') ? 'ring-4 ring-red-500' :'' }}"
                type="text" required id="name" name="name"
                value="{{ old('name', $user->name) }}">
        </label>
    </td><td>
    <tr><td>
        <label for="email">Email:
            @error('email')
                <span class="font-bold teZxt-red-700" role="alert"><strong>{{ $message }}</strong></span>
            @enderror
            <input class="rounded-md focus:ring-2 invalid:border-red-500
                {{ $errors->has('email') ? 'ring-4 ring-red-500' :'' }}"
                type="email" required id="email" name="email"
                value="{{ old('email', $user->email) }}">
        </label>
    </td><td>
    <tr><td>
        <label for="password">Password:
            @error('password')
                <span class="font-bold text-red-700" role="alert"><strong>{{ $message }}</strong></span>
            @enderror
            <input class="rounded-md focus:ring-2 invalid:border-red-500
                {{ $errors->has('password') ? 'ring-4 ring-red-500' :'' }}"
                type="password" id="password" name="password"
                value="{{ old('password', $user->password) }}">
        </label>
    </td><td>
    <tr><td>
        <label for="confirm-password">Confirm password:
            @error('confirm-password')
                <span class="font-bold text-red-700" role="alert"><strong>{{ $message }}</strong></span>
            @enderror
            <input class="rounded-md focus:ring-2 invalid:border-red-500
                {{ $errors->has('confirm-password') ? 'ring-4 ring-red-500' :'' }}"
                type="password" id="confirm-password" name="confirm-password"
                value="{{ old('confirm-password', $user->confirm_password) }}">
        </label>
    </td><td>
    <tr><td>
        <label for="callsign">Callsign:
            @error('callsign')
                <span class="font-bold text-red-700" role="alert"><strong>{{ $message }}</strong></span>
            @enderror
            <input class="rounded-md focus:ring-2 invalid:border-red-500
                {{ $errors->has('callsign') ? 'ring-4 ring-red-500' :'' }}"
                type="text" required id="callsign" name="callsign"
                value="{{ old('callsign', $user->callsign) }}">
        </label>
    </td><td>
    <tr><td>
        <label for="roles">Roles:
            @error('roles')
                <span class="font-bold text-red-700" role="alert"><strong>{{ $message }}</strong></span>
            @enderror
            <select name="roles[]" id="roles"
                class="rounded-md p-2 border border-slate-600 focus:ring-2 invalid:border-red-500"
                multiple>
                @foreach ($all_roles as $role)
                    <option value="{{ $role->name }}"
                        {{ (old('roles') === $role->name || $user->hasRole($role->name)) ? 'selected' : '' }}>
                        {{ $role->name }}
                    </option>
                @endforeach
            </select>
        </label>
    </td></tr>
    <tr><td>

    <div class="button-container">
        <div class="left-buttons">
            <x-primary-button class="mt-4">{{ __('Submit') }}</x-primary-button>
            <a href="{{ route('users.index') }}" class="inline-block ml-2">
                <x-secondary-button>{{ __('Cancel') }}</x-secondary-button>
            </a>
        </div>
        <div class="right-buttons">
            <x-danger-button name="delete" value="delete" class="mt-4 ml-2">{{ __('Delete User') }}</x-danger-button>
        </div>
    </div>
    </td></tr>
</table>
</form>
</x-app-layout>

resources/views/users/index.blade.php
<x-app-layout>
<div class="my-4">
    <div class="field-container mx-8">
        <div class="pull-left">
            <h2 class="mx-8">Users Management</h2>
        </div>
        <div class="pull-right">
            <a class="inline-block ml-2" href="{{ route('users.create') }}">
                <x-secondary-button>{{ __('Create new user') }}</x-secondary-button>
            </a>
        </div>
    </div>
</div>

@if ($message = Session::get('success'))
<div class="alert alert-success">
  <p>{{ $message }}</p>
</div>
@endif

<table class="table-auto *:border *:border-slate-600 my-8 mx-auto w-3/4">
 <tr class="*:border *:border-slate-600 *:w-2 *:bg-sky-200">
   <th>No</th>
   <th>Name</th>
   <th>Call sign</th>
   <th>Email</th>
   <th>Roles</th>
   <th width="280px">Action</th>
 </tr>
 @foreach ($data as $key => $user)
  <tr class="*:border *:border-slate-600 *:p-2">
    <td>{{ ++$i }}</td>
    <td>{{ $user->name }}</td>
    <td>{{ $user->callsign }}</td>
    <td>{{ $user->email }}</td>
    <td>
      @if(!empty($user->getRoleNames()))
        @foreach($user->getRoleNames() as $v)
           <label class="badge badge-success">{{ $v }}</label>
        @endforeach
      @endif
    </td>
    <td>
        <a href="{{ route('users.edit',$user->id) }}" class="inline-block mx-2">
            <x-primary-button>Edit</x-primary-button>
        </a>
        <a href="{{ route('users.destroy', $user->id) }}" class="inline-block mx-2">
            <x-danger-button name="delete" value="delete" >Delete</x-danger-button>
        </a>
    </td>
  </tr>
 @endforeach
</table>

</x-app-layout>

resources/views/users/show.blade.php
<x-app-layout>
<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="pull-left">
            <h2> Show User</h2>
        </div>
        <div class="pull-right">
            <a class="btn btn-primary" href="{{ route('users.index') }}"> Back</a>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>Name:</strong>
            {{ $user->name }}
        </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>Email:</strong>
            {{ $user->email }}
        </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>Callsign:</strong>
            {{ $user->callsign }}
        </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>Roles:</strong>
            @if(!empty($user->getRoleNames()))
                @foreach($user->getRoleNames() as $v)
                    <label class="badge badge-success">{{ $v }}</label>
                @endforeach
            @endif
        </div>
    </div>
</div>
</x-app-layout>