routes/web.php
<?php

use App\Http\Controllers\ProfileController;
use App\Http\Controllers\MeshPhoneController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\PageController;
use App\Http\Controllers\DashboardController;
use Illuminate\Support\Facades\Route;
use App\Helpers\Helper;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    // frontpage.md needs to reside in the public directory
    if (file_exists('frontpage.md')) {
        $front_page = file_get_contents('frontpage.md');
    } else {
        $front_page = '';
    }
    return view('welcome', compact('front_page'));
});

Route::Resource('page', PageController::class)
        ->only(['show']);

require __DIR__.'/auth.php';

Route::get('/dashboard', [DashboardController::class, 'index'])
    ->middleware(['auth', 'verified'])->name('dashboard');

Route::get('/info', function() {
    return phpinfo();
});

Route::get('/usertest', function() {
    return view('usertest');
});

Route::middleware('auth')->group(function () {
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
});

Route::group(['middleware' => ['auth']], function() {
    Route::resource('roles', RoleController::class);
    Route::resource('users', UserController::class);
});

Route::get('/meshphone/search', [MeshPhoneController::class, 'search'])
    ->name('meshphone.search');
Route::resource('meshphone', MeshPhoneController::class)
    ->only(['index', 'create', 'store', 'edit', 'update', 'destroy'])
    ->middleware(['auth']);
Route::get('/meshphone/{id}/delete', [MeshPhoneController::class, 'destroy'])
    ->name('meshphone.delete')
    ->middleware(['auth']);
Route::Resource('meshphone', MeshPhoneController::class)
        ->only(['show']);

Route::get('/network_json', function () {
    return redirect('/api/network_json');
});
Route::get('/network_xml_v2', function () {
    return redirect('/api/network_xml_v2');
});
Route::get('/network_xml_v1', function () {
    return redirect('/api/network_xml_v1');
});

app/Models/MeshPhone.php
<?php

namespace App\Models;

use MongoDB\Laravel\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class MeshPhone extends Model
{
    use HasFactory;

    const MAX_LATENCY_HISTORY = 12;

    /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = "network";

    /**
     * The primary key associated with the table.
     *
     * @var string
     */
    // protected $primaryKey = '_id';
    // protected $keyType = 'string';

    /**
     * Get the columns that should receive a unique identifier.
     *
     * @return array<int, string>
     */
    public function uniqueIds(): array
    {
        return ['_id'];
    }

    /**
     * The database connection that should be used by the model.
     *
     * @var string
     */
    protected $connection = 'mongodb';

    /**
     * The model's default values for attributes.
     *
     * @var array
     */
    protected $attributes = [
        'trunks' => [],
        'office_codes' => [],
        'pbx_status' => PbxStatus::Unknown->name,
        'pbx_type' => PbxType::Unknown->name,
    ];

    protected $dates = ['created_at', 'updated_at', 'checkin_at'];
    protected $casts = [
        'checkin_at' => 'datetime',
    ];
    protected $dateFormat = "Y-m-d  H:i:s";

    protected $collection = "network";
    protected $fillable = [
        'name',
        'admin_callsign',
        'admin_name',
        'admin_phone',
        'admin_email',
        'hostname',
        'ip_address',
        'latitude',
        'longitude',
        'location',
        'network',
        'pbx_type',
        'office_codes',
        'trunks',
        'pbx_status',
        'gen_script_version',
        'gen_script_name',
    ];

    public function updateTrunkLatency(string $pbx_name, int $latency) {
        //info("MeshPhone::updateTrunkLatency($pbx_name, $latency)");
        $trunks = $this->trunks;
        foreach($trunks as $key=>$entry) {
            if ($entry['pbx_name'] == $pbx_name) {
                // Add $latency to the front of latency_history and
                // truncate array to MAX_LATENCY_HISTORY
                $trunks[$key]['latency_history'] = array_merge([ $latency ],
                    array_slice($trunks[$key]['latency_history'] ?? [], 0,
                        MeshPhone::MAX_LATENCY_HISTORY-1));
                // Recalculate the average latency and store it
                $trunks[$key]['latency'] = (int)(array_sum($trunks[$key]['latency_history']) / count($trunks[$key]['latency_history']));
            }
        }
        $this->trunks = $trunks;
    }

}

app/Http/Controllers/MeshPhoneController.php
<?php

namespace App\Http\Controllers;

use App\Models\MeshPhone;
use App\Models\PbxType;
use App\Models\PbxStatus;
use App\Models\PbxPermission;
use Illuminate\Support\Arr;
use Illuminate\Http\Request;
use Illuminate\Http\RedirectResponse;
use Illuminate\View\View;
use MongoDB\Laravel\Eloquent\Model;
use App\Http\Requests\MeshPhoneRequest;
use App\Helpers\Helper;
//use Illuminate\Database\Eloquent\Collection;

class MeshPhoneController extends Controller
{
    const VALIDATIONS = array(
        'name' => 'required|string|uppercase|max:16|not_regex:/\s/|not_regex:/^\d+$/',
        'admin_name' => 'required|string',
        'admin_email' => 'required|string|email',
        'admin_phone' => 'required|string|regex:/^\d{3}-\d{4}$/',
        'admin_callsign' => 'required|string|uppercase|min:3',
        'location' => 'required|string',
        'latitude' => 'required|numeric',
        'longitude' => 'required|numeric',
        'hostname' => 'nullable|string|max:64',
        'ip_address' => 'nullable|ip|string',
        'network' => 'nullable',
        'pbx_type' => 'required|string',
        'office_codes' => 'array',
        'trunks' => 'array',
        'pbx_status' => 'required|string',
    );

    /**
     * Display a listing of the resource.
     */
    public function index(): View
    {
        // $pbx = MeshPhone::where('location', '=', 'DeLand, FL')->get();
        return view('meshphone.index');
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create(): View
    {
        info('MeshPhoneController.create()');

        $pbx = MeshPhone::factory()->make();
        $pbx->pbx_status = PbxStatus::Provisioning->name;

        return view('meshphone.create', [
            'pbx' => $pbx,
            'edit' => 1,
        ]);
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(MeshPhoneRequest $request): RedirectResponse
    {
        info('MeshPhoneController.store($request)');

        // just make sure ......
        $user = $request->user();
        if (!$user->hasPermissionTo(PbxPermission::CreatePBX)) {
            info("ERROR: {$user->callsign} attempted to create a PBX but does not have permission");
            return to_route('meshphone.index')->with('error', 'No permission to create PBX');
        }

        // Process any validation that needs to be done
        $validated = $request->validate(MeshPhoneController::VALIDATIONS);
        $errors = Helper::validateDialplan($request);
        if ($errors) {
            return redirect()->back()->withInput()->withErrors($errors);
        }

        Helper::resolveTrunks($request, $validated);

        // add office code for trunks being added
        if (array_key_exists('trunks', $validated)) {
            foreach($validated['trunks'] as &$trunk) {
                if (Arr::exists($trunk, 'office_code') == false) {
                    $trunk['office_code'] = Helper::firstOfficeCode($trunk['pbx_name']);
                }
            }
        }

        MeshPhone::create($validated);

        return to_route('meshphone.index')->with('success', 'PBX record stored successfully!');
    }

    /**
     * Display the specified resource.
     */
    public function show($id): View
    {
        info("MeshPhoneController.show($id)");

        return view('meshphone.show', [
            'pbx' => MeshPhone::where('_id', '=', $id)->first(),
            'edit' => 0,
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit($id): View
    {
        info("MeshPhoneController::edit({{$id}})");

        return view('meshphone.edit', [
            'pbx' => MeshPhone::where('_id', '=', $id)->get()->first(),
            'edit' => 1,
        ]);
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(MeshPhoneRequest $request, MeshPhone $meshPhone)
    {
        info('MeshPhoneController.update($request)');
        $user = $request->user();

        // Is the request flagged to be deleted?
        if ($request->delete == "delete") {
            info('Request indicates that record should be deleted');
            return to_route('meshphone.delete', $request->_id);
        }

        // Process any validation that needs to be done
        $needed_validations = Arr::only(MeshPhoneController::VALIDATIONS, array_keys($request->all()));
        $validated = $request->validate($needed_validations);
        $errors = Helper::validateDialplan($request);
        if ($errors) {
            return redirect()->back()->withInput()->withErrors($errors);
        }

        if ($user->hasAnyPermission([PbxPermission::CreateTrunk,
                                     PbxPermission::EditTrunk,
                                     PbxPermission::DeleteTrunk])) {
            Helper::resolveTrunks($request, $validated);

            if (array_key_exists('trunks', $validated)) {
                // add office code for trunks being added
                foreach($validated['trunks'] as &$trunk) {
                    if (Arr::exists($trunk, 'office_code') == false) {
                        $trunk['office_code'] = Helper::firstOfficeCode($trunk['pbx_name']);
                    }
                }
            } elseif ($user->hasPermissionTo(PbxPermission::DeleteTrunk)) {
                // trunks were validated, but nothing exists, create empty array
                $validated['trunks'] = array();
            }
        }

        $record = MeshPhone::find($request->_id);
        $record->update($validated);

        if ($user->hasPermissionTo(PbxPermission::EditPBX)) {
            $old_pbx_name = $request->input('orig_name');
            if ($validated['name'] != $old_pbx_name) {
                // PBX name is being changed. Update all trunks.
                foreach($validated['trunks'] as $trunk) {
                    Helper::removeTrunkFromPbx($old_pbx_name, $trunk['pbx_name']);
                    Helper::addTrunkToPbx($validated['name'], $trunk['pbx_name']);
                }
            }
        }

        return to_route('meshphone.index')->with('success', 'PBX record updated successfully!');
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy($id)
    {
        info("MeshPhoneController::destroy($id)");

        if (!$user->hasPermissionTo(PbxPermission::DeletePBX)) {
            info("ERROR: {$user->callsign} attempted to delete a PBX but does not have permission");
            return to_route('meshphone.index')->with('error', 'No permission to delete PBX');
        }

        $record = MeshPhone::where('_id', '=', $id);
        $record->delete();

        return to_route("meshphone.index")->with('success', 'PBX record deleted');
    }

    // This function is required to trigger a record to be deleted from the
    // edit screen.
    public function delete($id)
    {
        info("MeshPhoneController::delete($id)");
        return route("meshphone.destroy", $id);
    }

    public function search(Request $req)
    {
        info('MeshPhoneController->search($request)');
        $term = $req['search_for'];

        $results = MeshPhone::whereAny([
            'name', 'admin_name', 'admin_email', 'admin_phone',
            'admin_callsign', 'location', 'network', 'hostname',
            'ip_address'], 'LIKE', "%$term%")
            ->orWhere('office_codes.office_code', '=', $term)
            ->orderBy('name', 'asc')->get();

        return view("meshphone.index")->with('results', $results);
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;
use Illuminate\View\View;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     */
    public function render(): View
    {
        return view('layouts.app');
    }
}

app/View/Components/MeshPhone/SearchBox.php
<?php

namespace App\View\Components\MeshPhone;

use Closure;
use Illuminate\Contracts\View\View;
use Illuminate\View\Component;

class SearchBox extends Component
{
    /**
     * Create a new component instance.
     */
    public function __construct()
    {
        //
    }

    /**
     * Get the view / contents that represent the component.
     */
    public function render(): View|Closure|string
    {
        return view('components.mesh-phone.search-box');
    }
}

resources/views/meshphone/create.blade.php
<x-app-layout>
    <div class="max-w-2xl mx-auto p-4 sm:p-6 lg:p-8">
        <form method="POST" name="create_meshphone" id="create_meshphone" action="{{ route("meshphone.store") }}" >
            @csrf
            @include('meshphone/partials/meshphone', ['pbx' => $pbx])

            <x-primary-button class="mt-4">{{ __('Submit') }}</x-primary-button>
            <a href="{{ route('meshphone.index') }}">{{ __('Cancel') }}</a>
    </form>

    </div>
</x-app-layout>

resources/views/meshphone/edit.blade.php
@use('App\Models\PbxPermission')
<x-app-layout>
    <div class="max-w-2xl mx-auto p-4 sm:p-6 lg:p-8">
        <form method="POST" action="{{ route('meshphone.update', $pbx) }}">
            @csrf
            @method('patch')
            @include('meshphone/partials/meshphone', ['edit' => 1])


            <div class="button-container">
                <div class="left-buttons">
                    <x-primary-button class="mt-4">{{ __('Submit') }}</x-primary-button>
                    <a href="{{ route('meshphone.index') }}" class="inline-block ml-2">
                        <x-secondary-button>{{ __('Cancel') }}</x-secondary-button>
                    </a>
                </div>
                <div class="right-buttons">
                    @can(PbxPermission::DeletePBX)
                    <x-danger-button name="delete" value="delete" class="mt-4 ml-2">{{ __('Delete PBX') }}</x-danger-button>
                    @endcan
                </div>
            </div>
        </form>
    </div>
</x-app-layout>

resources/views/meshphone/index.blade.php
@use('App\Models\PbxStatus')
@use('App\Models\PbxPermission')
@use('Illuminate\Support\Arr')
<x-app-layout>
    <div class="max-w-2xl mx-auto p-4 sm:p-6 lg:p-8">
        <x-input-error :messages="$errors->get('message')" class="mt-2" />
        @if ($errors->any())
                <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
                </ul>
            @endif
        @if(session()->has('success'))
            <div class="p-4 sm:p-8 bg-white shadow sm:rounded-lg">
                <p class='font-xl text-green-600'>{{ session()->get('success') }}</p>
            </div>
        @endif

        <br/>
        @can(PbxPermission::CreatePBX)
        <a href="{{ route("meshphone.create") }}"><x-primary-button class="mt-4">{{ __('Add new PBX') }}</x-primary-button></a>
        @endcan
        <x-mesh-phone.search-box/>
    </div>

    @if( ! empty($results))
    <table class="table-auto *:border *:border-slate-600 my-8 mx-auto w-3/4">
        <caption class="font-extrabold text-2xl">Search results</caption>
        <tr class="*:border *:border-slate-600 *:w-2 *:bg-sky-200">
            <th>PBX name</th><th>PBX status</th><th>Location</th><th>Admin</th><th>Hostname</th>
        </tr>
        @foreach($results as $entry)
        <tr class="*:border *:border-slate-600 *:p-2"><td>
            @auth
                <a class="text-blue-600 hover:underline" href="{{ route('meshphone.edit', $entry) }}">{{ $entry->name }}</a>
            @else
                <a class="text-blue-600 hover:underline" href="{{ route('meshphone.show', $entry) }}">{{ $entry->name }}</a>
            @endauth
        </td>
        @if($entry->pbx_status == PbxStatus::Inactive->name)
        <td class="bg-indigo-200">
        @elseif($entry->pbx_status == PbxStatus::Active->name)
        <td class="bg-green-200">
        @elseif($entry->pbx_status == PbxStatus::Unknown->name)
        <td class="bg-gray-300">
        @elseif($entry->pbx_status == PbxStatus::Maintenance->name)
        <td class="bg-red-200">
        @elseif($entry->pbx_status == PbxStatus::Provisioning->name)
        <td class="bg-yellow-200">
        @elseif($entry->pbx_status == PbxStatus::Decommission->name)
        <td class="bg-purple-200">
        @else
        <td>
        @endif
            {{ $entry->pbx_status }}
            @if (Arr::exists($entry, 'checkin_at') && $entry->checkin_at->DiffInHours(now()) < 8)
                @svg('uiw-cloud-upload', 'icon px-1')
            @elseif (Arr::exists($entry, 'checkin_at'))
                @svg('uiw-cloud-upload-o', 'icon px-1')
            @endif
            @if (count($entry->trunks) == 0)
                @svg('uiw-stop', 'icon px-1')
            @endif
        </td><td>
            {{ $entry->location }}
        </td><td>
            {{ $entry->admin_name }}, {{ $entry->admin_callsign }}
            <a href="mailto:{{ $entry->admin_email }}?subject=MeshPhone%20Request">
                @svg('uiw-mail-o', 'icon px-2')
            </a>
        </td><td>
            {{ $entry->hostname }}
        </td></tr>
        @endforeach
    </table>

    <table class="table-auto *:border *:border-slate-600 my-8 mx-auto w-3/4">
        <tr>
            <td>@svg('uiw-cloud-upload', 'icon px-1') PBX has checked in within the last 8 hours</td>
            <td>@svg('uiw-cloud-upload-o', 'icon px-1') PBX checked in over 8 hours ago</td>
            <td>@svg('uiw-stop', 'icon px-1') PBX has no trunks</td>
        </tr>
    </table>
    @endif


</x-app-layout>

resources/views/meshphone/show.blade.php
<x-app-layout>
    <div class="max-w-2xl mx-auto p-4 sm:p-6 lg:p-8">
        @auth
        <form method="get" action="{{ route('meshphone.index') }}">
        @else
        <form method="get" action="/">
        @endauth

            @include('meshphone/partials/meshphone', ['edit' => 0])

            <x-primary-button class="mt-4">{{ __('Return') }}</x-primary-button>
        </form>
    </div>
</x-app-layout>